const hallData = [
  {
    id: "1",
    numberOfSeats: 50,
    amenities: ["Ac", "chairs", "discolights"],
    price: 5000,
    bookedStatus: "confirmed",
    customerName: "Sandeep",
    date: "05-feb-2023",
    startTime: "10-feb-2023 at 12PM",
    endTime: "11-feb-2020 at 11am",
    RoomId: 201,
    RoomType: "Duplex",
  },
  {
    id: "2",
    numberOfSeats: 80,
    amenities: ["Ac", "chairs", "discolights"],
    price: 5000,
    bookedStatus: "hold",
    customerName: "Rajesh",
    date: "20-feb-2023",
    startTime: "23-feb-2023 at 12PM",
    endTime: "24-feb-2023 at 11am",
    RoomId: 202,
    RoomType: "Duplex",
  },
  {
    id: "3",
    numberOfSeats: 40,
    amenities: ["Ac", "chairs"],
    price: 3000,
    bookedStatus: "hold",
    customerName: "Aswin",
    date: "02-apr-2023",
    startTime: "12-apr-2023 at 12PM",
    endTime: "13-apr-2023 at 11am",
    RoomId: 101,
    RoomType: "Classic",
  },
  {
    id: "4",
    numberOfSeats: 150,
    amenities: ["Ac", "chairs", "discolights"],
    price: 5000,
    bookedStatus: "confirmed",
    customerName: "Suresh",
    date: "03-may-2023",
    startTime: "15-may-2023 at 12PM",
    endTime: "16-may-2023 at 11am",
    RoomId: 203,
    RoomType: "Duplex",
  },
  {
    id: "5",
    numberOfSeats: 200,
    amenities: ["Ac", "chairs", "discolights", "buffet"],
    price: 9000,
    bookedStatus: "confirmed",
    customerName: "Vidhya",
    date: "26-may-2023",
    startTime: "01-jun-2023 at 12PM",
    endTime: "02-jun-2023 at 11am",
    RoomId: 301,
    RoomType: "Suite",
  },
  {
    id: "6",
    numberOfSeats: 200,
    amenities: ["Ac", "chairs", "discolights", "buffet"],
    price: 9200,
    bookedStatus: "confirmed",
    customerName: "Suresh",
    date: "28-may-2023",
    startTime: "06-jun-2023 at 12PM",
    endTime: "07-jun-2023 at 11am",
    RoomId: 302,
    RoomType: "Suite",
  },
  {
    id: "7",
    numberOfSeats: 150,
    amenities: ["Ac", "chairs", "discolights"],
    price: 5000,
    bookedStatus: "",
    customerName: "",
    date: "",
    startTime: "",
    endTime: "",
    RoomId: 204,
    RoomType: "Duplex",
  },
  {
    id: "8",
    numberOfSeats: 40,
    amenities: ["Ac", "chairs"],
    price: 3000,
    bookedStatus: "",
    customerName: "",
    date: "",
    startTime: "",
    endTime: "",
    RoomId: 102,
    RoomType: "Classic",
  }
]

export default hallData